mysite_django_tutorial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('portfolio.urls')),
    path('creditapp/', include('creditapp.urls')),
    path('polls/', include('polls.urls')),
    path('viewonsnow/', include('viewonsnow.urls')),
    prefix_default_language=True,
)

polls/urls.py
"""
Url for polls app
"""

from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view() , name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

viewonsnow/urls.py
"""
Url for viewOnSnow app
"""

from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from . import views


app_name = 'viewonsnow'


urlpatterns = [
    # ex: /
    path('', views.viewonsnow_index, name='viewonsnow_index'),
    #example: viewonsnow/api/data/11
    path('api/data/<int:calc_id>', views.get_data, name='api-data'),
    path('api/chart/data/', views.ChartData.as_view()),
]

viewonsnow/models.py
from django.db import models

# Create your models here.

class Snow (models.Model):

    #wartość początkowa bez śniegu 
    input_before_snow = models.CharField(max_length=400)

    #wartość po opadzie śniegu 
    output_after_snow = models.CharField(max_length=400)

    def __str__(self):
        return self.input_before_snow

viewonsnow/forms.py
from django import forms

from .models import Snow

class SnowCreateForm(forms.ModelForm):
    """
    Index for snow app, Main window
    """
    class Meta:
        model = Snow
        fields = ['input_before_snow',
                 ]

viewonsnow/views.py
from django.http.response import Http404, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import View
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from rest_framework.views import APIView
from rest_framework.response import Response

from .functions import viewOnSnow

from .models import Snow
from .forms import SnowCreateForm

User = get_user_model()

# Create your views here.

def viewonsnow_index(request):
    #clear jest przekazywany w momencie czyczczenia okna 
    if request.method == 'POST' and request.POST.get("clear") == None:
        form = SnowCreateForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            try:
                #pobieramy wprowadzone dane i przerabiamy na listę
                inputString = post.input_before_snow
                inputList = [int(s) for s in inputString.split(',')]

                #funkcja oczekuje listy, wartość początkowa przed opadami śniegu
                #funkcja zwraca stan po opadach śniegu 
                outputList = viewOnSnow(inputList)
                post.output_after_snow = ','.join([str(elem) for elem in outputList])
                post.save()

            except ValueError:
                context = _("The entered value is not valid.")
                return render(request, 'viewonsnow/main.html', {
                    'form': form,
                    'error_message': str(context),
                })

            except NotImplementedError:
                return render(request, 'viewonsnow/main.html', {
                    'form': form,
                    'error_message': "Error!",
                })
            
            else:
                form_data = form.cleaned_data
                return render (request, 'viewonsnow/main.html',{
                    'form': form_data,
                    'output_after_snow': post.output_after_snow,
                    'calc': True,
                    'calc_id': post.id,
                })

        else:
            return render(request, 'viewonsnow/main.html',
            {
                'form': form,
                'error_message': form.errors.values(),
            })     

    else:
        form = SnowCreateForm()
    return render(request, 'viewonsnow/main.html',
                  {'form': form})

def get_data(request, calc_id, **kwargs):
    
    calc = get_object_or_404(Snow, pk = calc_id)
    #konwersja stringu z DB do listy
    outputList = [int(s) for s in calc.output_after_snow.split(',')]
    inputList = [int(s) for s in calc.input_before_snow.split(',')]

    #utworzenie listy dla labels
    size = len(outputList)
    labels = list(range(1, size + 1))

    data = {
        "id": calc_id,
        "labels": labels,
        "output_after_snow": outputList,
        "input_before_snow": inputList,
    }

    return JsonResponse(data) #http response



class ChartData(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_count = User.objects.all().count()
        labels = ['Users', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange']
        default_items = [qs_count, 2, 3, 4, 5, 6]
        data = {
            "labels": labels,
            "default": default_items,
        }
        return Response(data)

    

viewonsnow/templates/viewonsnow/main.html
<!DOCTYPE html>
{% load static i18n %}
{% load l10n %}


<html lang="en">
<head>
  <title>Snow application</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% include 'base/css.html' %}
  {% include 'base/js_top.html' %}
  {{ calc_id|json_script:"calc_id" }}

</head>
<body class="bg-light">

  {# navbar start #}
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light shadow-sm">
    <div class="container-lg ">
      <a class="navbar-brand text-primary fw-bold fs-4" href="#">{% trans "Snow application" %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto flex-nowrap">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false"> {% trans "Language" %}</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% get_current_language as LANGUAGE_CODE %}                
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}

                {% comment %} {% for lang in languages %}
                  <li><a class='dropdown-item' href="/{{lang.code}}/{% url 'viewonsnow:viewonsnow_index' %}"> {{ lang.name_translated  }}</a> </li>
                {% endfor %} {% endcomment %}

                {% for lang_code, lang_name in LANGUAGES %}
                  {% language lang_code %}
                    <li><a class='dropdown-item' href="{% url 'viewonsnow:viewonsnow_index'  %}">{{ lang_name }}</a> </li>
                  {% endlanguage %}
                {% endfor %}
              
            </ul>
          </li>
          <li class="nav-item mx-2"></li>
          <li >
            <input type="checkbox" class="btn-check " id="darkButton" autocomplete="off">
            <label class="btn btn-outline-primary px-3" for="darkButton"><i class="fas fa-moon"></i></label><br>
          </li>
        </ul>
      </div>


      
    </div>
  </nav>
  {# navbar end #}
    
    {# form start #}
    <section class="pt-5 pb-4 mt-5 ">
        <div class="container-lg py-2">
            <form method="post">
            {% csrf_token %}
                
                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_input_before_snow" class="col-form-label">{% trans "Input before snow" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" id="id_input_before_snow" class="form-control" name="input_before_snow" required {% if calc %} value="{{ form.input_before_snow }}" disabled {% else %} value="" {% endif %} >
                    </div>
                </div>

    
                
                <input  class="btn my-2 btn-primary"  {% if calc %}type="submit" value="{% trans "Clear" %}" name="clear"
                                                      {% else %}type="submit" value="{% trans "Calculation" %}"{% endif %}>
            </form>

            
            {% comment %} {% if calc %}
            <div class="row g-3 my-1">
                <div class="col-md-3">
                    <label for="id_output_after_snow" class="col-form-label">{% trans "output_after_snow" %}</label>
                </div>
                <div class="col-md-3">
                    <input type="text" id="id_output_after_snow" class="form-control" name="output_after_snow" value="{{ output_after_snow }}"  disabled>
                </div>
            </div>

            {% endif %} {% endcomment %}


            {% if error_message %} 
                <p><strong> {{error_message}} </strong></p> 
            {% endif %}
        </div>
    </section>
    {# form end #}

    {# chart start #}
    <section class="chart ">
      <div class="container-lg py-4">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <canvas id="myChart_before" width="400" height="400"></canvas>
          </div>
          <div class="col-md-6">
            <canvas id="myChart_after" width="400" height="400"></canvas>
          </div>
        </div>
      </div>
    </section>
    {# chart end #}
    


  <footer class="footer border-top py-4">
    <div class="container-lg">
      <div class="row">
        <div class="col-lg-12">
          <p class="m-0 text-center text-muted">&copy; 2021 Karol N. </p>
        </div>
      </div>
    </div>
  </footer>

<script src="{% static 'viewonsnow/js/bootstrap.bundle.min.js' %} "></script>
<script src="{% static 'viewonsnow/js/dark-mode-switch.min.js' %} "></script>
<script src="{% static 'viewonsnow/js/api-data.js' %}"></script>

</body>
</html>