creditapp/urls.py
"""
Url for creditapp app
"""

from django.urls import path
from . import views

app_name = 'creditapp'

urlpatterns = [
    # ex: /creditapp/
    path('', views.Credit_new, name='Credit_new'),
    # ex: /creditapp/5/results/
    ##path('<int:pk>/results/', views.ResultsView , name='ResultsView'),
    # ex: /creditapp/5/calc/
    #path('<int:credit_id>/calc/', views.calc, name='calc'),
]

mysite_django_tutorial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('portfolio.urls')),
    path('creditapp/', include('creditapp.urls')),
    path('polls/', include('polls.urls')),
    path('viewonsnow/', include('viewonsnow.urls')),
    prefix_default_language=True,
)

polls/urls.py
"""
Url for polls app
"""

from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view() , name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

creditapp/models.py
from django.db import models

# Create your models here.

class Credit (models.Model):

    #nazwa kalkulacji, nazwa własna 
    credit_name_text = models.CharField(max_length=200, unique=True, )
    #oprocentowanie
    interest_rate = models.DecimalField(max_digits=4, decimal_places=2, null=False)
    #liczba rat
    installmentsVal = models.DecimalField(max_digits=4, decimal_places=0, null=False)
    #wartosc kredytu
    creditValue = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    #miesięczny przychód
    monthlyIncome = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    #miesięczne wydatki
    monthlyExpenses = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    
    #Możliwą kwotę pożyczki
    #wartosc kredytu #creditValue na razie
    #kwotę całkowitą do spłaty
    totalAmountRepaid = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    #czas na jaki został rozłożony okres spłaty
    #TO DO
    #miesięczną ratę
    monthlyInstallment = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    #data wykonania kalkulacji
    creditResultDate = models.DateTimeField('calculation date', null=True)

    def __str__(self):
        return self.credit_name_text

creditapp/forms.py
from django import forms

from .models import Credit

class CreditCreateForm(forms.ModelForm):
    """
    Index for credit app, Main window
    """
    class Meta:
        model = Credit
        fields = ['credit_name_text',
                'interest_rate',
                'installmentsVal',
                'creditValue',
                'monthlyIncome',
                'monthlyExpenses']

creditapp/views.py
"""
Views for credit app
"""
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.template import loader
from django.views import generic

from .models import Credit
from .forms import CreditCreateForm

def Credit_new(request):
    if request.method == 'POST':
        form = CreditCreateForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            try:
                q = 1 + ((post.interest_rate/100)/12)
                vInstallment = round(post.creditValue * (pow(q,post.installmentsVal)) * ((q-1)/(pow(q,post.installmentsVal)-1)), 2)
                post.totalAmountRepaid = vInstallment * post.installmentsVal
                post.monthlyInstallment = vInstallment
                post.creditResultDate = timezone.now()

                # Czy użytkownika stać na kredyt?, 
                # Kwota jaka pozostanie po obliczeniu 
                # różnicy pomiędzy przychodem a wydatkami                
                maxMonthlyInstallment = post.monthlyIncome - post.monthlyExpenses

                if post.monthlyInstallment > maxMonthlyInstallment:
                    return render(request, 'creditapp/credit_create_form.html', {
                        'form': form,
                        'error_message': "Error!, You cannot get a loan, the loan installment exceeds your creditworthiness",
                    })
                else:    
                    post.save()
            except ZeroDivisionError:
                return render(request, 'creditapp/credit_create_form.html', {
                    'form': form,
                    'error_message': "Error!, You can't divide by zero!",
                })
            else:
                #return redirect('creditapp:ResultsView',pk=post.pk)
                form_data = form.cleaned_data
                return render (request, 'creditapp/credit_create_form.html',{
                    'form': form_data,
                    'totalAmountRepaid': post.totalAmountRepaid,
                    'monthlyInstallment': post.monthlyInstallment,
                    'calc': True,
                })
        else: 
            return render(request, 'creditapp/credit_create_form.html', {
                    'form': form,
                    'error_message': form.errors.values(),
               })
            

            


    else:
        form = CreditCreateForm()
    return render(request, 'creditapp/credit_create_form.html',
                  {'form': form})

#def ResultsView(request, pk):
#    post = get_object_or_404(Credit, pk=pk)    
#    return render(request, 'creditapp/results.html', {'form': post,})
    

creditapp/templates/creditapp/credit_create_form.html
<!DOCTYPE html>
{% load static i18n %}
{% load l10n %}


<html lang="en">
<head>
  <title>Credit application</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}">  
  <link rel="stylesheet" href="{% static 'portfolio/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static  'portfolio/css/dark-mode.css' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>
<body class="bg-light">

  {# navbar start #}
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light shadow-sm">
    <div class="container-lg ">
      <a class="navbar-brand text-primary fw-bold fs-4" href="#">{% trans "Credit application" %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto flex-nowrap">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false"> {% trans "Language" %}</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% get_current_language as LANGUAGE_CODE %}                
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}

                {% comment %} {% for lang in languages %}
                  <li><a class='dropdown-item' href="/{{lang.code}}"> {{ lang.name_translated  }}</a> </li>
                {% endfor %} {% endcomment %}

                {% for lang_code, lang_name in LANGUAGES %}
                  {% language lang_code %}
                    <li><a class='dropdown-item' href="{% url 'creditapp:Credit_new'  %}">{{ lang_name }}</a> </li>
                  {% endlanguage %}
                {% endfor %}
              
            </ul>
          </li>
          <li class="nav-item mx-2"></li>
          <li >
            <input type="checkbox" class="btn-check " id="darkButton" autocomplete="off">
            <label class="btn btn-outline-primary px-3" for="darkButton"><i class="fas fa-moon"></i></label><br>
          </li>
        </ul>
      </div>


      
    </div>
  </nav>
  {# navbar end #}
    
    {# form start #}
    <section class="pt-5 pb-4 mt-5 ">
        <div class="container-lg py-2">
            <form method="post">
            {% csrf_token %}
                {# {{ form.as_p  }} #}
                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_credit_name_text" class="col-form-label">{% trans "Credit name text" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" id="id_credit_name_text" class="form-control" name="credit_name_text" {% if calc %} value="{{ form.credit_name_text }}" disabled {% endif %} >
                    </div>
                </div>

                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_interest_rate" class="col-form-label">{% trans "Interest rate" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_interest_rate" class="form-control" name="interest_rate" step="0.01" {% if calc %} value="{{ form.interest_rate|unlocalize }}" disabled {% endif %}>
                    </div>
                </div>

                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_installmentsVal" class="col-form-label">{% trans "Number of installments" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_installmentsVal" class="form-control" name="installmentsVal" {% if calc %} value="{{ form.installmentsVal|unlocalize }}" disabled {% endif %}>
                    </div>
                </div>

                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_creditValue" class="col-form-label">{% trans "Credit value" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_creditValue" class="form-control" name="creditValue" step="0.01" {% if calc %} value="{{ form.creditValue|unlocalize }}" disabled {% endif %}>
                    </div>
                </div>

                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_monthlyIncome" class="col-form-label">{% trans "Monthly income" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_monthlyIncome" class="form-control" name="monthlyIncome" step="0.01" {% if calc %} value="{{ form.monthlyIncome|unlocalize }}" disabled {% endif %}>
                    </div>
                </div>

                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_monthlyExpenses" class="col-form-label">{% trans "Monthly expenses" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_monthlyExpenses" class="form-control" name="monthlyExpenses" step="0.01" {% if calc %} value="{{ form.monthlyExpenses|unlocalize }}" disabled {% endif %}>
                    </div>
                </div>
                
                <input type="submit" class="btn my-2 btn-primary"  {% if calc %}value="Clear"{% else %}value="Calculation"{% endif %}>
            </form>

            {% if calc %}
              <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_totalAmountRepaid" class="col-form-label">{% trans "Total amount repaid" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_totalAmountRepaid" class="form-control" name="totalAmountRepaid" value="{{ totalAmountRepaid|unlocalize }}" step="0.01" disabled>
                    </div>
                </div>

                <div class="row g-3 my-1">
                    <div class="col-md-3">
                        <label for="id_monthlyInstallment" class="col-form-label">{% trans "Monthly installment" %}</label>
                    </div>
                    <div class="col-md-3">
                        <input type="number" id="id_monthlyInstallment" class="form-control" name="monthlyInstallment" value="{{ monthlyInstallment|unlocalize  }}" step="0.01" disabled>
                    </div>
                </div>
            {% endif %}


            {% if error_message %} 
                <p><strong> {{error_message}} </strong></p> 
            {% endif %}
        </div>
    </section>
    {# form end #}



  <footer class="footer border-top py-4">
    <div class="container-lg">
      <div class="row">
        <div class="col-lg-12">
          <p class="m-0 text-center text-muted">&copy; 2021 Karol N. </p>
        </div>
      </div>
    </div>
  </footer>

<script src="{% static 'portfolio/js/bootstrap.bundle.min.js' %} "></script>
<script src="{% static 'portfolio/js/dark-mode-switch.min.js' %} "></script>
</body>
</html>

creditapp/templates/creditapp/results.html
<h1>
    {{ form.credit_name_text }}
</h1>
<form>
    <p><label for="interest_rate">Interest rate:</label>
    <input type="number" id="interest_rate" name="interest_rate" value="{{ form.interest_rate }}" step="0.01" disabled></p>

    <p><label for="installmentsVal">Number of installments:</label>
    <input type="number" id="installmentsVal" name="installmentsVal" value="{{ form.installmentsVal }}" disabled></p>

    <p><label for="id_creditValue">Credit value:</label> 
    <input type="number" id="id_creditValue" name="creditValue" value="{{ form.creditValue }}" step="0.01" disabled></p>
    
    <p><label for="id_monthlyIncome">Monthly income:</label> 
    <input type="number" id="id_monthlyIncome" name="monthlyIncome" value="{{ form.monthlyIncome }}" step="0.01" disabled></p>
    
    <p><label for="id_monthlyExpenses">Monthly expenses:</label> 
    <input type="number" id="id_monthlyExpenses" name="monthlyExpenses" value="{{ form.monthlyExpenses }}" step="0.01" disabled></p>

    <p>-----------------</p>

    <p><label for="id_totalAmountRepaid">Total amount repaid:</label> 
    <input type="number" id="id_totalAmountRepaid" name="totalAmountRepaid" value="{{ form.totalAmountRepaid }}" step="0.01" disabled></p>

    <p><label for="id_monthlyInstallment">Monthly installment:</label> 
    <input type="number" id="id_monthlyInstallment" name="monthlyInstallment" value="{{ form.monthlyInstallment }}" step="0.01" disabled></p>

</form>    